version: '3'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    tty: true
    ports:
      - "8085:80"
    networks:
      - fullcycle
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app
    command: node index.js
    entrypoint: dockerize -wait tcp://mysql_db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - fullcycle
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - fullcycle

networks:
  fullcycle:
    driver: bridge
